quadrotor_env:
   camera: no
   sim_dt: 0.02
   max_t: 50.0
   add_camera: yes

quadrotor_dynamics:
  mass: 0.73
  arm_l: 0.17
  motor_omega_min: 150.0 # motor rpm min
  motor_omega_max: 3000.0 # motor rpm max
  motor_tau: 0.0001 # motor step response
  thrust_map: [1.3298253500372892e-06, 0.0038360810526746033, -1.7689986848125325]
  kappa: 0.016 # rotor drag coeff
  omega_max: [6.0, 6.0, 6.0]  # body rate constraint (x, y, z) 

rl:
  ang_vel_coeff: 0.01  # reward coefficient for control actions
  crash_penalty: -10

race_track:
  #gate_1: [-10, 0, 2.5, 0] #x, y, z, alpha
  #gate_2: [0, 10, 2.5, 90]
  #gate_3: [10, 0, 2.5, 180]
  #gate_4: [0, -10, 2.5, 270]
  gate_1: [12.5, 12.5, 6.25, 0]
  gate_2: [12.5, 12.5, 2.5, 180]
  gate_3: [10, 0, 2.5, 180]
  gate_4: [11.25, 0, 6.25, 0]
  gate_5: [12.5, 0, 2.5, 180]
  gate_6: [5, -10, 2.5, 135]
  gate_7: [-12.5, -12.5, 2.5, 90]
  gate_8: [-5, 7.5, 2.5, 315]